// src/components/footer.tsx
import React from "react";
import { Container, Row, Col } from "react-bootstrap";

const Footer: React.FC = () => {
    return (
        <section id="footer">
            <Container id="footer-section" className="py-2" fluid>
                <Row>
                    <Col className="pt-3 d-flex justify-content-between align-items-center">
                        <p>
                            © 2020 <a href="https://github.com/ranmaru22">ranmaru22</a>
                        </p>
                        <p className="text-right">
                            Source code available on{" "}
                            <a href="https://github.com/ranmaru22/ranmaru22.github.io">GitHub</a>.
                        </p>
                    </Col>
                </Row>
            </Container>
        </section>
    );
};

export default Footer;

// src/components/Footer.vue
<template>
  <section id="footer">
    <div id="footer-section" class="container-fluid py-2">
      <div class="row">
        <div class="pt-3 d-flex justify-content-between align-items-center">
          <p>
            © 2020 –
            <a href="https://github.com/ranmaru22">Alex Sun (ranmaru22)</a>
          </p>
          <p class="text-right">
            Source code available on
            <a href="https://github.com/ranmaru22/ranmaru22.github.io">GitHub</a>
            .
          </p>
        </div>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({ name: "Footer" });
</script>
