// src/components/Header.vue
<template>
  <section id="home" class="pt-5">
    <div id="header-section" class="container-fluid p-5">
      <div class="row">
        <div class="col text-center pt-3">
          <img class="my-3" src="images/avataaars.svg" alt="Alex Sun" />
        </div>
      </div>
      <div class="row">
        <div class="col text-center">
          <h1 class="header">Hi, I'm Alex</h1>
          <h2 class="subheader">Programmer & Web Developer</h2>
        </div>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "HeaderSection"
});
</script>

// src/components/header.tsx
import React from "react";
import { Container, Row, Col } from "react-bootstrap";

const Header = () => {
    return (
        <section id="home">
            <Container id="headerSection" className="p-5" fluid>
                <Row>
                    <Col className="text-center">
                        <img className="mb-3" src="images/avataaars.svg" alt="Alex Sun" />
                    </Col>
                </Row>
                <Row>
                    <Col className="text-center">
                        <h1 className="header">Hi, I'm Alex</h1>
                        <h2 className="subheader">Programmer & Web Developer</h2>
                    </Col>
                </Row>
            </Container>
        </section>
    );
};

export default Header;
