// src/components/Navbar.vue
<template>
  <nav id="main-nav" class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Alex Sun</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#nav-collapse"
        aria-controls="nav-collapse"
        aria-expanded="false"
      >
        <span class="navbar-toggler-icon" />
      </button>
      <div id="nav-collapse" class="collapse navbar-collapse">
        <div class="navbar-nav ml-auto">
          <a class="nav-link" href="#home">Home</a>
          <a class="nav-link" href="#projects">Projects</a>
          <a class="nav-link" href="#about">About Me</a>
        </div>
      </div>
    </div>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Navbar"
});
</script>

// src/components/navbar.tsx
import React from "react";
import { Navbar, Nav, Container } from "react-bootstrap";

const NavBar: React.FC = () => {
    return (
        <>
            <Navbar id="mainNav" variant="dark" bg="dark" sticky="top" expand="lg">
                <Container fluid>
                    <Navbar.Brand href="#home">Alex Sun</Navbar.Brand>
                    <Navbar.Toggle aria-controls="responsive-navbar-nav" />
                    <Navbar.Collapse id="basic-navbar-nav">
                        <Nav defaultActiveKey="#home" className="ml-auto">
                            <Nav.Link href="#home">Home</Nav.Link>
                            <Nav.Link href="#projects">Projects</Nav.Link>
                            <Nav.Link href="#about">About Me</Nav.Link>
                            <Nav.Link href="#contact">Contact</Nav.Link>
                        </Nav>
                    </Navbar.Collapse>
                </Container>
            </Navbar>
        </>
    );
};

export default NavBar;
