// src/components/projects.tsx
import React from "react";
import { Container, CardColumns, Card } from "react-bootstrap";

export interface Project {
    image: string;
    alt: string;
    label: string;
    description: string;
    link: string;
}

// const ProjectCard: React.FC<{ project: Project }> = ({ project }) => {};

const Projects: React.FC<{ projects: Project[] }> = ({ projects }) => {
    return (
        <div id="projects">
            <Container className="p-5 text-justify" fluid="md">
                <h3>Creative Portfolio</h3>
                <CardColumns>
                    {projects.map((project, i) => (
                        <Card bg="light">
                            <Card.Img
                                className="project-img"
                                variant="top"
                                src={project.image}
                                alt={project.alt}
                            />
                            <Card.Body>
                                <Card.Title>{project.label}</Card.Title>
                                <Card.Text>{project.description}</Card.Text>
                            </Card.Body>
                            <Card.Footer>
                                <a href={project.link}>View on GitHub</a>
                            </Card.Footer>
                        </Card>
                    ))}
                </CardColumns>
            </Container>
        </div>
    );
};

export default Projects;

// src/components/Projects.vue
<template>
  <section id="projects" class="p-lg-5 pt-5">
    <div class="container-fluid container-lg mt-5 pt-5 text-justify">
      <h3 class="text-center text-md-left">Creative Portfolio</h3>
      <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xxl-4 g-4">
        <!-- CARD -->
        <div v-for="(project, idx) in projects" :key="idx" class="col">
          <div class="card h-100">
            <img class="card-img-top project-img" :src="project.image" :alt="project.alt" />
            <div class="card-body">
              <h4 class="card-title">{{ project.label }}</h4>
              <p class="card-text">{{ project.description }}</p>
            </div>
            <div class="card-footer text-center">
              <a :href="project.link">View on GitHub</a>
            </div>
          </div>
        </div>
        <!-- END CARD -->
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";
import { Project } from "types";

export default defineComponent({
  name: "Projects",
  props: {
    projects: { type: Object as PropType<Project[]>, required: true }
  }
});
</script>
